services:
  db:
    image: mysql:8.0
    container_name: db
    restart: unless-stopped
    env_file: .env
    environment:
      - MYSQL_DATABASE=$MYSQL_DB_NAME
    volumes:
      - ./db:/var/lib/mysql
    command: "--default-authentication-plugin=mysql_native_password"
    networks:
      - dampp-network

  php:
    depends_on:
      - db
    build:
      args:
        user: mandlenkosi
        uid: 1000
      context: ./
      dockerfile: php.dockerfile
    container_name: dampp_php
    restart: unless-stopped
    env_file: .env
    volumes:
      - ./app:/var/www/html
    networks:
      - dampp-network

  nginx:
    depends_on:
      - php
      - db
    build:
      args:
        user: mandlenkosi
        uid: 1000
      context: ./
      dockerfile: nginx.dockerfile
    container_name: dampp_nginx
    restart: unless-stopped
    ports:
      - "8088:80"
    volumes:
      - ./conf/nginx:/etc/nginx/conf.d
      - ./app:/var/www/html
    networks:
      - dampp-network

  phpmyadmin:
    depends_on:
      - db
    image: phpmyadmin/phpmyadmin:latest
    container_name: dampp_phpmyadmin
    restart: always
    env_file: .env
    ports:
      - 8180:80
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: $MYSQL_ROOT_PASSWORD
    networks:
      - dampp-network

networks:
  dampp-network:
    driver: bridge
